bsm/urls.py
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bsm.views.home', name='home'),
    # url(r'^bsm/', include('bsm.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^trans/', include('transaction.urls')),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transaction/urls.py
from django.conf.urls import patterns, url
from view import *


urlpatterns = patterns('',
		url(r'^$', home.index, name='home'),
		url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'transaction/login.html'}),
		url(r'^logout/$', logout.index, name='logout'),
		url(r'^nasabah/$', nasabah.index, name='nasabah'),
		url(r'^nasabah_kolektif/$', nasabah.index_kolektif, name='nasabah_kolektif'),
		url(r'^nasabah_add/$', nasabah.add, name='nasabah_add'),
		url(r'^nasabah_edit/(?P<nasabah_id>\d+)/$', nasabah.edit, name='nasabah_edit'),
		url(r'^nasabah_delete/$', nasabah.delete, name='nasabah_delete'),
		url(r'^vendor/$', vendor.index, name='vendor'),
		url(r'^vendor_add/$', vendor.add, name='vendor_add'),
		url(r'^vendor_edit/(?P<vendor_id>\d+)/$', vendor.edit, name='vendor_edit'),
		url(r'^pembelian/$', pembelian.index, name='pembelian'),
		url(r'^pembelian_add/$', pembelian.add, name='pembelian_add'),
		url(r'^penjualan/$', penjualan.index, name='penjualan'),
		url(r'^penjualan_add/$', penjualan.add, name='penjualan_add'),
		url(r'^konversi/$', konversi.index, name='konversi'),
		url(r'^konversi_add/$', konversi.add, name='konversi_add'),
		url(r'^penarikan/$', penarikan.index, name='penarikan'),
		url(r'^penarikan_add/(?P<nasabah_id>\d+)/$', penarikan.add, name='penarikan_add'),
		url(r'^kategori/$', kategori.index, name='kategori'),
		url(r'^kategori_edit/(?P<kategori_id>\d+)/$', kategori.edit, name='kategori_edit'),
		url(r'^kategori_add/$', kategori.add, name='kategori_add'),
		url(r'^nasabah_detail/(?P<nasabah_id>\d+)/$', nasabah.detail, name='nasabah_detail'),
		url(r'^vendor_detail/(?P<vendor_id>\d+)/$', vendor.detail, name='vendor_detail'),
		url(r'^pembelian_detail/(?P<pembelian_id>\d+)/$', pembelian.detail, name='pembelian_detail'),
		url(r'^pembelian_print/(?P<pembelian_id>\d+)/$', pembelian.print_version, name='pembelian_print'),
		url(r'^pembelian_del/(?P<pembelian_id>\d+)/$', pembelian.delete, name='pembelian_del'),
		url(r'^pembelian_edit/(?P<pembelian_id>\d+)/$', pembelian.edit, name='pembelian_edit'),
		url(r'^penjualan_detail/(?P<penjualan_id>\d+)/$', penjualan.detail, name='penjualan_detail'),
		url(r'^penjualan_print/(?P<penjualan_id>\d+)/$', penjualan.print_version, name='penjualan_print'),
		url(r'^penjualan_del/(?P<penjualan_id>\d+)/$', penjualan.delete, name='penjualan_del'),
		url(r'^penjualan_edit/(?P<penjualan_id>\d+)/$', penjualan.edit, name='penjualan_edit'),
		url(r'^penarikan_del/(?P<penarikan_id>\d+)/$', penarikan.delete, name='penarikan_del'),
		url(r'^konversi_detail/(?P<konversi_id>\d+)/$', konversi.detail, name='konversi_detail'),
		url(r'^konversi_del/(?P<konversi_id>\d+)/$', konversi.delete, name='konversi_del'),
		url(r'^stok_detail/(?P<stok_id>\d+)/$', report.stok_detail, name='stok_detail'),
		url(r'^penarikan_detail/(?P<penarikan_id>\d+)/$', penarikan.detail, name='penarikan_detail'),
		url(r'^laba_rugi/$', report.laba_rugi, name='laba_rugi'),
		url(r'^arus_barang/$', report.arus_barang, name='arus_barang'),
		url(r'^utang_nasabah_kolektif/$', report.utang_nasabah_kolektif, name='utang_nasabah_kolektif'),
		url(r'^utang_nasabah_individu/$', report.utang_nasabah_individu, name='utang_nasabah_individu'),
		url(r'^tonase_nasabah_kolektif/$', report.tonase_nasabah_kolektif, name='tonase_nasabah_kolektif'),
		url(r'^tonase_nasabah_individu/$', report.tonase_nasabah_individu, name='tonase_nasabah_individu'),
	)

transaction/models.py
from django.db import models
import datetime


class Nasabah(models.Model):
	ktp = models.CharField(null=True, blank=True, max_length=30)
	nama = models.CharField(max_length=50)
	alamat = models.TextField()
	telepon = models.CharField(null=True, blank=True,max_length=255)
	email = models.EmailField(null=True, blank=True)
	tanggal_lahir = models.DateField(null=True, blank=True)
	tanggal_daftar = models.DateField(default=datetime.date.today)
	foto = models.ImageField(null=True, blank=True, upload_to='nasabah')
	jenis = models.CharField(max_length=20, default="individu")
	nama_pj = models.CharField(null=True, blank=True, max_length=50)
	no_induk = models.CharField(null=True, blank=True, unique=True, max_length=50)
	def __unicode__(self):
		return str(self.id) + '-' + self.nama

	def is_safe_to_be_deleted(self):
		return self.pembelian_set.count() + self.penarikan_set.count() == 0

class Vendor(models.Model):
	nama = models.CharField(max_length=50)
	alamat = models.TextField()
	telepon = models.CharField(null=True, blank=True, max_length=30)
	email = models.EmailField(null=True, blank=True)
	tanggal_daftar = models.DateField(default=datetime.date.today)
	foto = models.ImageField(null=True, blank=True, upload_to='vendor')
	def __unicode__(self):
		return str(self.id) + '-' + self.nama

class ReportKategori(models.Model):
	nama = models.CharField(max_length=50)
	satuan = models.CharField(max_length=20)
	def __unicode__(self):
		return self.nama

class Kategori(models.Model):
	kode = models.CharField(max_length=5)
	nama = models.CharField(max_length=50)
	deskripsi = models.TextField()
	satuan = models.CharField(max_length=20)
	foto = models.ImageField(null=True, blank=True, upload_to='kategori')
	stabil = models.DecimalField(max_digits=15, decimal_places=2)
	fluktuatif = models.DecimalField(max_digits=15, decimal_places=2)
	report_kategori = models.ForeignKey('ReportKategori',default=1)
	def __unicode__(self):
		return self.kode + '-' + self.nama + ' (' + self.satuan + ')'

class Stok(models.Model):
	kategori = models.ForeignKey('Kategori')
	tanggal = models.DateField()
	jumlah = models.DecimalField(max_digits=8, decimal_places=2)
	harga = models.DecimalField(max_digits=15, decimal_places=2)
	def __unicode__(self):
		return self.kategori.kode + '-' + str(self.tanggal) + ' (' + str(int(self.jumlah)) + '$'+ str(int(self.harga)) +')'

class Pembelian(models.Model):
	nasabah = models.ForeignKey('Nasabah')
	stocks = models.ManyToManyField(Stok)
	tanggal = models.DateField()
	nota = models.CharField(max_length=20, null=True, blank=True)
	penarikan = models.ForeignKey('Penarikan', null=True, blank=True, on_delete=models.SET_NULL)
	penarikans = models.ManyToManyField('Penarikan', through='DetailPenarikan', related_name='penarikan_new', blank=True)
	def __unicode__(self):
		return self.nasabah.nama + '-' + str(self.tanggal)
	def total_value(self):
		return sum([stock.harga * stock.jumlah for stock in self.stocks.all()])
	def total_unit(self):
		return sum([stock.jumlah for stock in self.stocks.all()])
	def settled_value(self):
		return sum([detail_penarikan.jumlah for detail_penarikan in self.detailpenarikan_set.all()])
	def unsettled_value(self):
		return self.total_value() - self.settled_value();

class Penjualan(models.Model):
	vendor = models.ForeignKey('Vendor')
	stocks = models.ManyToManyField('Stok', through='DetailPenjualan')
	tanggal = models.DateField()
	nota = models.CharField(max_length=20, null=True, blank=True)
	def __unicode__(self):
		return self.vendor.nama + '-' + str(self.tanggal)

class DetailPenjualan(models.Model):
	penjualan = models.ForeignKey('Penjualan')
	stok = models.ForeignKey('Stok')
	jumlah = models.DecimalField(max_digits=8, decimal_places=2)
	harga = models.DecimalField(max_digits=15, decimal_places=2)


class Konversi(models.Model):
	tanggal = models.DateField()
	ins = models.ManyToManyField('Stok', through='DetailIn', related_name='stock_in_id')
	outs = models.ManyToManyField('Stok', related_name='stock_out_id')
	kode = models.CharField(max_length=20, null=True, blank=True)
	def __unicode__(self):
		return str(self.id) + '-' + str(self.tanggal)

class DetailIn(models.Model):
	konversi = models.ForeignKey('Konversi')
	stok = models.ForeignKey('Stok')
	jumlah = models.DecimalField(max_digits=8, decimal_places=2)

class Penarikan(models.Model):
	nasabah = models.ForeignKey('Nasabah')
	tanggal = models.DateField()
	total = models.DecimalField(max_digits=15, decimal_places=2)
	nota = models.CharField(max_length=20, null=True, blank=True)

class DetailPenarikan(models.Model):
	penarikan = models.ForeignKey('Penarikan')
	pembelian = models.ForeignKey('Pembelian')
	jumlah = models.DecimalField(max_digits=15, decimal_places=2)

transaction/forms.py
from django import forms
from django.forms import ModelForm
from transaction.models import Nasabah, Vendor, Pembelian, Kategori, Penjualan, Konversi, Penarikan
from transaction.db import q_remaining_dict, q_nasabah_detail_only, q_reclaimed_stocks, q_retrieve_pembelian_candidates

class NasabahForm(ModelForm):
	class Meta:
		model = Nasabah
		exclude = ('tanggal_daftar',)

class LoginForm(ModelForm):
	class Meta:
		model = Nasabah
		exclude = ('tanggal_daftar',)

class KategoriForm(ModelForm):
	class Meta:
		model = Kategori

class VendorForm(ModelForm):
	class Meta:
		model = Vendor
		exclude = ('tanggal_daftar',)
	def clean(self):
		cleaned_data = super(VendorForm, self).clean()
		c_nama = cleaned_data.get('nama')

		if 'Robeth' in c_nama:
			raise forms.ValidationError('Dont include Robeth in your name please :)')

		return cleaned_data

class PembelianForm(ModelForm):
	class Meta:
		model = Pembelian
		exclude = ('stocks',)

	def clean(self):
		cleaned_data = super(PembelianForm, self).clean()
		data = self.data

		if 'total' in data:
			limit = int(data['total'])
			i = 1
			while i <= limit:
				try:
					temp = Kategori.objects.get(id=data['stok'+str(i)])
				except Kategori.DoesNotExist :
					raise forms.ValidationError('Kategori '+ str(i)+ ' Does Not Exist')
				i += 1

			return cleaned_data
		else:
			raise forms.ValidationError('Total variable is not defined!')

class PenjualanForm(ModelForm):
	class Meta:
		model = Penjualan
		exclude = ('stocks',)
	def clean(self):
		cleaned_data = super(PenjualanForm, self).clean()
		data = self.data
		remaining = q_remaining_dict()

		if 'penjualan_id' in data:
			reclaimed_stocks = q_reclaimed_stocks(data['penjualan_id'])
			for k,v in reclaimed_stocks.iteritems():
				remaining[k]['jumlah_penjualan'] -= v
				remaining[k]['sisa'] += v

		if 'total' in data:
			limit = int(data['total'])
			i = 1
			while i <= limit:
				try:
					temp = Kategori.objects.get(kode=data['stok'+str(i)])
					if (float(data['jumlah'+str(i)]) > float(remaining[data['stok'+str(i)]]['sisa'])):
						raise forms.ValidationError('Kategori '+ data['stok'+str(i)]+ ' Insufficient. Stok:' + str(float(remaining[data['stok'+str(i)]]['sisa'])))
				except Kategori.DoesNotExist :
					raise forms.ValidationError('Kategori '+ str(i)+ ' Does Not Exist')
				except Exception as e:
					raise forms.ValidationError(str(e))
				i += 1

			return cleaned_data
		else:
			raise forms.ValidationError('Total variable is not defined!')

class KonversiForm(ModelForm):
	class Meta:
		model = Konversi
		exclude = ('ins', 'outs')

	def clean(self):
		cleaned_data = super(KonversiForm, self).clean()
		data = self.data
		remaining = q_remaining_dict()

		if 'total' in data:
			limit = int(data['total'])
			i = 1
			while i <= limit:
				try:
					temp = Kategori.objects.get(kode=data['stok_in'+str(i)])
					if (float(data['jumlah_in'+str(i)]) > float(remaining[data['stok_in'+str(i)]]['sisa'])):
						raise forms.ValidationError('Kategori '+ data['stok_in'+str(i)]+ ' Insufficient. Stok:' + str(float(remaining[data['stok_in'+str(i)]]['sisa'])))
				except Kategori.DoesNotExist :
					raise forms.ValidationError('Kategori '+ str(i)+ ' Does Not Exist')
				i += 1

			return cleaned_data
		else:
			raise forms.ValidationError('Total variable is not defined!')


class PenarikanForm(ModelForm):
	class Meta:
		model = Penarikan

	def clean(self):
		cleaned_data = super(PenarikanForm, self).clean()
		data = self.data

		if self.errors:
			return cleaned_data

		pembelians = q_retrieve_pembelian_candidates(data['nasabah'])
		pembelians_amount = sum([pembelian.total_value() for pembelian in pembelians])

		if pembelians_amount < float(data['total']):
			raise forms.ValidationError('Total penarikan (' + data['total'] +') > nilai pembelian (' + str(pembelians_amount) + ')')
		else:
			return cleaned_data

transaction/templates/transaction/advanced_window.html
<div class="row">
	<div class="span6 offset1">
		<div id="adv-window" class="well">
			<form class="form-horizontal" method="GET" action="{% url 'pembelian'%}" >
				<div class="control-group">
					<label class="control-label" for="inputDate">Tanggal</label>
					<div class="controls">
						<input class="input-small" id="inputDate" placeholder="Mulai" type="text" name="inputDate">
						<input class="input-small" id="inputEnd" placeholder="Akhir" type="text" name="inputEnd">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputValue">Nilai</label>
					<div class="controls">
						<input class="input-small" id="inputValue" placeholder="Min" type="text">
						<input class="input-small" id="inputVEnd" placeholder="Max" type="text">
					</div>
				</div>
				<div class="control-group">
					<div class="controls">
						<button type="submit" class="btn btn-primary"><i class="icon-refresh"></i>Refresh</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

transaction/templates/transaction/penarikan_detail.html
{% extends "transaction/base-ui.html" %}
{% load humanize %}
{% load transaction_util %}
{% load staticfiles %}
{% block judul %}
Penarikan {{ penarikan.id }}
{% endblock judul%}
{% block nav_penarikan %}active{% endblock nav_penarikan %}
{% block content %}
<div class="container">
	<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Tutup</span></button>
					<h3 id="myModalLabel" class="modal-header">Hapus Penarikan {{ penarikan.id }} </h3>
				</div>
				<div class="modal-body">
					<p>Semua link pembelian yang terkait akan ikut terhapus.</p>
					<p>Apakah anda yakin?</p>
				</div>
				<div class="modal-footer">
					<form action="{% url 'penarikan_del' penarikan.id %}" method="POST">
						{% csrf_token %}
						<button class="btn" data-dismiss="modal" aria-hidden="true" >Batal</button>
						<button type="submit" class="btn btn-danger">Ya</button>
						<input type="hidden" name="penarikan_id" value="{{ penarikan.id }}"/>
					</form>
				</div>
			</div>
		</div>
	</div>

	<div>
		<h3>Penarikan {{ penarikan.id }}</h3>
		<div class="form-inline pull-right">
			<a href="" class="btn btn-danger" data-toggle="modal" data-target="#myModal">Hapus</a>
		</div>
		<div class="row">
			<div class="col-md-6 well">
				<div class="form-horizontal">
					<div class="form-group">
						<label class="control-label col-md-2">Nasabah</label>
						<div class="col-md-10">
							<p class="form-control-static">{% nasabah_url penarikan.nasabah.id %} {{ penarikan.nasabah.nama }}</p>
						</div>
					</div>

					<div class="form-group">
						<label class="control-label col-md-2">Nota</label>
						<div class="col-md-10">
							<p class="form-control-static">{{ penarikan.nota }}</p>
						</div>
					</div>

					<div class="form-group">
						<label class="control-label col-md-2" for="id_total">Total</label>
						<div class="col-md-10">
							<div class="input-group">
								<div class="input-group-addon">Rp</div>
								<input id="id_total" type="number" class="form-control" value="{{ penarikan.total }}" readonly>
							</div>
						</div>
					</div>

					<div class="form-group">
						<label class="control-label col-md-2">Tanggal</label>
						<div class="col-md-10">
							<p class="form-control-static">{{ penarikan.tanggal|date:"Y-m-d" }}</p>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-6">
				<h3>Daftar Pembelian</h3>
				<table class="table table-striped table-bordered table-hover table-condensed" id="pembelian-list">
					<thead>
						<tr>
							<td class="center">Kode</td>
							<td class="center">Tanggal</td>
							<td class="center">Lunas</td>
							<td class="center">Total</td>
						</tr>
					</thead>
					<tbody>
					{% for detail_penarikan in penarikan.detailpenarikan_set.all %}
						<tr>
							<td>{%pembelian_url detail_penarikan.pembelian.id%}</td>
							<td class="center">{{detail_penarikan.pembelian.tanggal|date:"Y-m-d"}}</td>
							<td class="right">{{detail_penarikan.jumlah|floatformat:2|intcomma}}</td>
							<td class="right">{{detail_penarikan.pembelian.total_value|floatformat:2|intcomma}}</td>
						</tr>
					{% endfor%}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
{% endblock content %}
{% block js_extra %}
{{ block.super }}
<script type="text/javascript">
	$(document).ready(function(){
		$("#pembelian-list").dataTable({
			"bPaginate": false,
			"bLengthChange": false,
			"bFilter": true,
			"bSort": true,
			"bInfo": false,
			"bAutoWidth": false
		});
	});
</script>
<script src="{% static "js/jquery.dataTables.js" %}"></script>
{% endblock js_extra %}

transaction/templates/transaction/penarikan_edit.html
{% extends "transaction/base-ui.html" %}
{% load humanize %}
{% load transaction_util %}
{% load staticfiles %}
{% block judul %}
Edit Penarikan {{penarikan.id}}
{% endblock judul%}
{% block nav_penarikan %}active{% endblock nav_penarikan %}
{% block content %}
<div class="container">
	<form action="{% url 'penarikan_edit' penarikan.id %}" method="POST">
		<h3>Edit Penarikan {{penarikan.id}}</h3>
		{% csrf_token %}
		{% if form.errors %}
		<div class="row">
			<div class="alert alert-danger alert-dismissable" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<strong>Error(s):</strong> {{ form.errors }}
			</div>
		</div>
		{% endif %}
		<div class="row">
			<div class="col-md-6 well">
				<div class="form-horizontal">
					<div class="form-group">
						<label class="control-label col-md-2" for="{{ form.nasabah.id_for_label }}" >{{ form.nasabah.label }}</label>	
						<div class="col-md-10">
							<select class="easyui-combobox form-control" name="nasabah" id="{{form.nasabah.id_for_label}}">
								{% for n in form.nasabah.field.queryset %}
								<option value="{{ n.id  }}">{{n.nama}}</option>
								{% endfor %}
							</select>
						</div>
					</div>
					
					<div class="form-group">
						<label class="control-label col-md-2" for="{{ form.nota.id_for_label}}" >{{ form.nota.label }}</label>	
						<div class="col-md-10">
							{{ form.nota|add_class:"form-control" }}
						</div>
					</div>
					
					<div class="form-group">
						<label class="control-label col-md-2" for="{{ form.total.id_for_label}}" >{{ form.total.label }}</label>	
						<div class="col-md-10">
							<div class="input-group">
								<div class="input-group-addon">Rp</div>
								<input id="id_total" type="number" class="form-control"  name="total" value="{{ form.total.value }}" readonly>
							</div>
						</div>
					</div>

					<div class="form-group">
						<label class="control-label col-md-2" for="{{ form.tanggal.id_for_label}}" >{{ form.tanggal.label }}</label>	
						<div class="col-md-10">
							{{ form.tanggal|add_class:"form-control" }}
						</div>
					</div>
					<button class="btn btn-primary pull-right" type="submit">Selesai</button>
				</div>
			</div>
			<div class="col-md-6">
				<table class="table table-striped table-bordered table-hover table-condensed" id="pembelian-list">
					<thead>
						<tr>
							<td></td>
							<td>Kode</td>
							<td>Tanggal</td>
							<td>Nilai</td>
							<td>Tonase</td>
						</tr>
					</thead>
					<tbody>
					{% for p in form.pembelians.field.queryset %}
						<tr>
							<td><input type="checkbox" name="pembelians" value="{{p.id}}"{% if  p.id|slugify in form.pembelians.value%}
								checked
							{% endif %}/></td>
							<td>{%pembelian_url p.id%}</td>
							<td class="center">{{p.tanggal|date:"Y-m-d"}}</td>
							<td class="right">{{p.total_value|floatformat:2|intcomma}}</td>
							<td class="right">{{p.total_unit|floatformat:2|intcomma}}</td>
						</tr>	
					{% endfor%}
					</tbody>
				</table>
			</div>
		</div>
	</form>
</div>
{% endblock content %}
{% block js_extra %}
{{ block.super }}
<script type="text/javascript">
	$(document).ready(function(){
		$( "#id_{{ form.tanggal.html_name}}" ).datepicker({ dateFormat: "yy-mm-dd",
			"showAnim" : "slideDown",
			"changeMonth" : true,
			"changeYear" : true});

		$("#pembelian-list input[type='checkbox']").click(function(index){
			 	updateTotal();
		});

		$("#pembelian-list").dataTable({
			"bPaginate": false,
			"bLengthChange": false,
			"bFilter": true,
			"bSort": true,
			"bInfo": false,
			"bAutoWidth": false
		});

		function updateTotal(){
			var total = 0;

			$("#pembelian-list input:checked").each(function(index, element){
				total += parseFloat($(this).parent().next().next().next().text().replace(/[^0-9\.]+/g,""));
			});

			$('input[name="total"]').val(total);
		}
		updateTotal();
	});
</script>
<script src="{% static "js/jquery.dataTables.js" %}"></script>
{% endblock js_extra %}

transaction/templates/transaction/penjualan_edit.html
{% extends "transaction/base-ui.html" %}
{% load humanize %}
{% load transaction_util %}
{% load staticfiles %}
{% block judul %}
Edit Penjualan {{ penjualan.id }}
{% endblock judul%}
{% block nav_penjualan %}active{% endblock nav_penjualan %}
{% block content %}
<div class="container">
	<form id="form-penjualan" class="form-horizontal" action="{% url 'penjualan_edit' penjualan.id %}" method="post">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 well">
				<input type="hidden" name="penjualan_id" value="{{ penjualan.id }}" />
				{% csrf_token %}
				<h3>Edit Penjualan</h3>
				{% if form.errors %}
				<div class="alert">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<strong>Error:</strong> {{ form.errors }}
				</div>
				{% endif %}
				<div class="form-group">
					<label class="control-label col-md-2" for="id_{{ form.tanggal.html_name}}" >{{ form.tanggal.label }}</label>
					<div class="col-md-10">
						{{ form.tanggal|add_class:"form-control" }}
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-md-2" for="id_{{ form.nota.html_name}}" >{{ form.nota.label }}</label>
					<div class="col-md-10">
						{{ form.nota|add_class:"form-control" }}
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-md-2" for="id_{{ form.vendor.html_name}}" >{{ form.vendor.label }}</label>
					<div class="col-md-10">
						<input type="text" id="vendor-ui" class="form-control" />
						<input type="hidden" id="id_vendor" name="vendor" />
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<h3>Daftar Barang Penjualan</h3>
			<div class="col-md-12">
				<table id="inputs" class="table table-hover table-condensed">
					{#  #}
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="toolbar">
					<button type=button class="add-input btn" >+</button>
				</div>
			</div>
			<div class="col-md-2 col-md-offset-6">
				<button class="btn btn-primary" type="submit">Selesai</button>
			</div>
		</div>
	</form>
</div>
{% endblock content %}
{% block js_extra %}
{{ block.super }}
<script type="text/javascript">
var options = jQuery.parseJSON('{{ remaining|jsonify_simple|safe }}');
var penjualan = jQuery.parseJSON('{{ penjualan|jsonify_simple|safe }}');
var accounts = jQuery.parseJSON('{{ vendor_dictionary|jsonify|safe }}');
var initialData = jQuery.parseJSON('{{ initial_vendor|jsonify|safe }}');

$(document).ready(function() {
    $("#id_{{ form.tanggal.html_name}}").datepicker({
        dateFormat: "yy-mm-dd",
        "showAnim": "slideDown",
        "changeMonth": true,
        "changeYear": true
    });

    StockInput($("table#inputs"), {
    	form: $("#form-penjualan"),
    	counterName: "total",
		fields: {
			amount: {
				name: "jumlah"
			},
			price: {
				name: "harga"
			}
		},
        addButton: $("button.add-input"),
        autoComplete: {
        	stockData: options,
        	fieldName: "stok",
        	key: "kode",
			additionalInfo: {
	        	key: "sisa",
	        	htmlTag: "<code/>",
	        	renderCallback: function(ui,value){
	        		ui.text(value + " tersisa");
	        	}
	        }
    	},
    	initial: penjualan.detailPenjualanList
    });

		NasabahAutocomplete($('#vendor-ui'), $('#id_vendor'), accounts, initialData);
});
</script>
{% endblock js_extra %}